@extends('layouts.app')

@section('title', 'Shopping Cart | Digitron Computers UAE')

@section('whatsapp_message', 'Hello Digitron Computers UAE, I need help with the items in my cart. Please assist me.')

@section('page','cart')

@section('fullwidth')
{{-- Hero Section with Video Background --}}
<section class="relative h-[50vh] min-h-[400px] overflow-hidden flex items-center justify-center pt-28 sm:pt-32 md:pt-36 pb-24">
    <!-- Video Background -->
    <div class="absolute inset-0 w-full h-full z-0">
        <img src="{{ asset('images/slide1.jpg') }}"
            alt="Tech Background"
            class="w-full h-full object-cover opacity-60 scale-110 parallax-bg">
        <div class="absolute inset-0 bg-gradient-to-b from-[#070A12]/15 via-[#070A12]/35 to-[#070A12]/55"></div>
    </div>

    <!-- Animated Grid -->
    <div class="absolute inset-0 bg-grid-pattern opacity-[0.05] pointer-events-none"></div>

    <!-- Floating Elements (generated by JS) -->
    <div id="cartParticles" class="absolute inset-0 overflow-hidden pointer-events-none"></div>

    <!-- Content -->
    <div class="relative z-10 text-center px-4 parallax-content">
        <div class="inline-flex items-center gap-2 px-4 py-2 rounded-full border border-brand-accent/30 bg-brand-accent/10 mb-6">
            <i class="bi bi-cart3 text-brand-accent"></i>
            <span class="text-brand-accent text-sm font-bold uppercase tracking-wider">Your Selection</span>
        </div>

        <h1 class="text-5xl md:text-7xl font-display font-black mb-4 tracking-tight">
            SHOPPING <span class="text-transparent bg-clip-text bg-gradient-to-r from-brand-accent to-brand-secondary">CART</span>
        </h1>

        <p class="text-lg text-gray-400 max-w-xl mx-auto">
            Review your items and proceed to secure checkout. Premium hardware awaits.
        </p>

        <!-- Cart Stats -->
        <div class="flex items-center justify-center gap-8 mt-8">
            <div class="text-center">
                <div class="text-2xl font-bold text-white" id="cart-count">{{ $count }}</div>
                <div class="text-xs text-gray-500 uppercase tracking-wider">Items</div>
            </div>
            <div class="w-px h-10 bg-white/20"></div>
            <div class="text-center">
                <div class="text-2xl font-bold text-brand-accent" id="cart-total-hero">AED {{ number_format($total) }}</div>
                <div class="text-xs text-gray-500 uppercase tracking-wider">Total</div>
            </div>
        </div>
    </div>
</section>
@endsection

@section('content')

@php
$hasUnavailableItems = collect($items)->contains(fn($item) => ($item['stock'] ?? '') === 'Out of Stock');
@endphp

<section class="py-12 -mt-8 relative z-20">
    <div class="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {{-- Cart Items --}}
        <div class="lg:col-span-8 space-y-6">
            <!-- Progress Steps -->
            <div class="glass-panel rounded-2xl p-6 border border-white/10 mb-8">
                <div class="flex items-center justify-between relative">
                    <div class="absolute top-1/2 left-0 right-0 h-0.5 bg-white/10 -translate-y-1/2"></div>
                    <div class="absolute top-1/2 left-0 w-1/3 h-0.5 bg-brand-accent -translate-y-1/2"></div>

                    @foreach(['Cart', 'Shipping', 'Payment', 'Complete'] as $index => $step)
                    <div class="relative flex flex-col items-center gap-2 z-10">
                        <div class="w-10 h-10 rounded-full flex items-center justify-center text-sm font-bold transition-all
                                {{ $index === 0 ? 'bg-brand-accent text-black shadow-lg shadow-brand-accent/50' : 
                                   ($index === 1 ? 'bg-white/10 text-white border border-white/20' : 'bg-white/5 text-gray-500') }}">
                            {{ $index + 1 }}
                        </div>
                        <span class="text-xs {{ $index === 0 ? 'text-white' : 'text-gray-500' }}">{{ $step }}</span>
                    </div>
                    @endforeach
                </div>
            </div>

            <!-- Cart Header -->
            <div class="flex items-center justify-between mb-4">
                <h2 class="text-xl font-bold flex items-center gap-2">
                    Cart Items <span class="text-sm text-gray-500 font-normal">({{ $items->count() }})</span>
                </h2>
                <button id="btnClearCart"
                    type="button"
                    class="text-sm text-gray-400 hover:text-brand-danger transition-colors flex items-center gap-1 group">
                    <i class="bi bi-trash3 group-hover:animate-bounce"></i> Clear Cart
                </button>
            </div>

            <!-- Items List -->
            <div class="space-y-4" id="cart-items">
                @foreach($items as $index => $item)
                <div class="cart-item glass-panel rounded-2xl p-6 border border-white/10 hover:border-brand-accent/30 transition-all group relative overflow-hidden" data-id="{{ $item['id'] }}" data-price="{{ $item['price'] }}" data-qty="{{ $item['qty'] }}">
                    <!-- Hover Glow -->
                    <div class="absolute inset-0 bg-gradient-to-r from-brand-accent/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none"></div>

                    <div class="relative flex flex-col md:flex-row gap-6">
                        <!-- Image -->
                        <div class="relative w-full md:w-32 h-32 rounded-xl overflow-hidden bg-white/5 flex-shrink-0">
                            <img src="{{ $item['image'] }}" alt="{{ $item['name'] }}" class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500">
                            <div class="absolute top-2 left-2">
                                <span class="px-2 py-1 rounded text-[10px] font-bold {{ $item['stock'] === 'In Stock' ? 'bg-emerald-500/20 text-emerald-400' : 'bg-orange-500/20 text-orange-400' }}">
                                    {{ $item['stock'] }}
                                </span>
                            </div>
                        </div>

                        <!-- Details -->
                        <div class="flex-1 min-w-0">
                            <div class="flex items-start justify-between gap-4">
                                <div>
                                    <div class="text-xs text-gray-500 mb-1">{{ $item['sku'] }}</div>
                                    <h3 class="font-bold text-lg text-white group-hover:text-brand-accent transition-colors mb-1">{{ $item['name'] }}</h3>
                                    <p class="text-sm text-gray-400 mb-3">{{ $item['specs'] }}</p>

                                    <div class="flex items-center gap-4 text-xs text-gray-500">
                                        <span class="flex items-center gap-1"><i class="bi bi-shield-check text-emerald-400"></i> {{ $item['warranty'] }} Warranty</span>
                                        <span class="flex items-center gap-1"><i class="bi bi-truck text-brand-accent"></i> Free Shipping</span>
                                    </div>
                                </div>

                                <button class="js-cart-remove text-gray-500 hover:text-brand-danger transition-colors p-2 hover:bg-brand-danger/10 rounded-lg"
                                    type="button"
                                    data-id="{{ $item['id'] }}">
                                    <i class="bi bi-x-lg"></i>
                                </button>
                            </div>

                            <div class="flex items-end justify-between mt-4 pt-4 border-t border-white/5">
                                <!-- Quantity -->
                                <div class="flex items-center gap-3">
                                    <span class="text-sm text-gray-400">Qty:</span>
                                    <div class="flex items-center border border-white/10 rounded-lg overflow-hidden">
                                        <button type="button"
                                            class="js-qty-minus w-10 h-10 flex items-center justify-center hover:bg-white/5 transition-colors {{ $item['stock'] === 'Out of Stock' ? 'opacity-50 cursor-not-allowed' : '' }}"
                                            data-id="{{ $item['id'] }}"
                                            {{ $item['stock'] === 'Out of Stock' ? 'disabled' : '' }}>
                                            <i class="bi bi-dash"></i>
                                        </button>

                                        <input type="number"
                                            value="{{ $item['qty'] }}"
                                            min="1" max="10"
                                            class="js-qty-input w-12 text-center bg-transparent text-sm font-bold focus:outline-none {{ $item['stock'] === 'Out of Stock' ? 'opacity-50 cursor-not-allowed' : '' }}"
                                            data-id="{{ $item['id'] }}"
                                            {{ $item['stock'] === 'Out of Stock' ? 'disabled' : '' }} />

                                        <button type="button"
                                            class="js-qty-plus w-10 h-10 flex items-center justify-center hover:bg-white/5 transition-colors {{ $item['stock'] === 'Out of Stock' ? 'opacity-50 cursor-not-allowed' : '' }}"
                                            data-id="{{ $item['id'] }}"
                                            {{ $item['stock'] === 'Out of Stock' ? 'disabled' : '' }}>
                                            <i class="bi bi-plus"></i>
                                        </button>
                                    </div>
                                </div>

                                <!-- Price -->
                                <div class="text-right">
                                    <div class="text-2xl font-bold text-white item-total" data-single="{{ $item['price'] }}">
                                        AED {{ number_format($item['price'] * $item['qty']) }}
                                    </div>
                                    <div class="text-sm text-gray-500">AED {{ number_format($item['price']) }} each</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                @endforeach
            </div>

            <!-- Continue Shopping -->
            <a href="{{ route('shop') }}" class="inline-flex items-center gap-2 text-gray-400 hover:text-brand-accent transition-colors group">
                <i class="bi bi-arrow-left group-hover:-translate-x-1 transition-transform"></i>
                Continue Shopping
            </a>
        </div>

        {{-- Order Summary --}}
        <div class="lg:col-span-4">
            <div class="sticky top-24 space-y-6">
                <!-- Summary Card -->
                <div class="glass-panel rounded-2xl p-6 border border-white/10 shadow-2xl shadow-brand-accent/5">
                    <h3 class="text-xl font-bold mb-6 flex items-center gap-2">
                        <i class="bi bi-receipt text-brand-accent"></i> Order Summary
                    </h3>

                    <!-- Calculations -->
                    <div class="space-y-3 mb-6 text-sm">

                        <div class="flex justify-between text-gray-400">
                            <span>Subtotal ({{ $count }} items)</span>
                            <span>AED {{ number_format($subtotal, 2) }}</span>
                        </div>

                        <div class="flex justify-between text-gray-400">
                            <span>Shipping</span>
                            <span>
                                @if($shipping == 0)
                                <span class="text-emerald-400">FREE</span>
                                @else
                                AED {{ number_format($shipping, 2) }}
                                @endif
                            </span>
                        </div>

                        <div class="flex justify-between text-gray-400">
                            <span>Estimated Tax</span>
                            <span>AED {{ number_format($tax, 2) }}</span>
                        </div>

                        @if($discount > 0)
                        <div class="flex justify-between text-brand-accent">
                            <span>Discount</span>
                            <span class="text-red-400">
                                - AED {{ number_format($discount, 2) }}
                            </span>
                        </div>
                        @endif

                    </div>

                    <!-- Coupon -->
                    <div class="mb-6">

                        @if(session('success'))
                        <div class="text-green-400 text-sm mb-2">{{ session('success') }}</div>
                        @endif

                        @if(session('error'))
                        <div class="text-red-400 text-sm mb-2">{{ session('error') }}</div>
                        @endif

                        <form method="POST" action="{{ route('cart.applyCoupon') }}">
                            @csrf
                            <div class="flex gap-2">
                                <input
                                    type="text"
                                    name="code"
                                    placeholder="Enter coupon code"
                                    class="flex-1 px-4 py-3 rounded-xl bg-white/5 border border-white/10 text-sm focus:outline-none focus:border-brand-accent"
                                    required>
                                <button
                                    type="submit"
                                    class="px-4 py-3 rounded-xl bg-white/10 hover:bg-brand-accent hover:text-black transition-colors font-medium text-sm">
                                    Apply
                                </button>
                            </div>
                        </form>
                    </div>

                    <!-- Total -->
                    <div class="border-t border-white/10 pt-4 mb-6">
                        <div class="flex justify-between items-end">
                            <span class="text-gray-400">Total</span>
                            <div class="text-right">
                                <div class="text-xs text-gray-500 mb-1">AED</div>
                                <div class="text-4xl font-display font-bold text-white" id="final-total">{{ number_format($total, 2) }}</div>
                            </div>
                        </div>
                        <div class="text-xs text-gray-500 mt-2 text-right">Including VAT</div>
                    </div>

                    <!-- Checkout Button -->
                    @if($hasUnavailableItems)
                    <button type="button"
                        disabled
                        class="w-full py-4 rounded-xl bg-white/10 text-gray-500 font-bold text-lg opacity-60 cursor-not-allowed flex items-center justify-center gap-2">
                        Remove out of stock items to continue
                    </button>
                    @else
                    <button id="btnCheckout"
                        type="button"
                        data-auth="{{ auth()->check() ? 1 : 0 }}"
                        data-checkout-url="{{ route('checkout') }}"
                        class="w-full py-4 rounded-xl bg-gradient-to-r from-brand-accent to-brand-secondary text-black font-bold text-lg hover:shadow-lg hover:shadow-brand-accent/30 transition-all flex items-center justify-center gap-2 group">
                        Proceed to Checkout
                        <i class="bi bi-arrow-right group-hover:translate-x-1 transition-transform"></i>
                    </button>
                    @endif

                    <!-- Payment Icons -->
                    <div class="flex items-center justify-center gap-4 mt-4 opacity-50">
                        <i class="bi bi-credit-card-2-front text-2xl"></i>
                        <i class="bi bi-paypal text-2xl"></i>
                        <i class="bi bi-apple text-2xl"></i>
                        <span class="text-xs">Secure SSL Encryption</span>
                    </div>
                </div>

                <!-- Trust Badges -->
                <div class="glass-panel rounded-2xl p-4 border border-white/10">
                    <div class="grid grid-cols-2 gap-4 text-center">
                        <div class="flex flex-col items-center gap-2">
                            <div class="w-12 h-12 rounded-full bg-emerald-500/10 flex items-center justify-center text-emerald-400">
                                <i class="bi bi-shield-check text-xl"></i>
                            </div>
                            <span class="text-xs text-gray-400">Secure Payment</span>
                        </div>
                        <div class="flex flex-col items-center gap-2">
                            <div class="w-12 h-12 rounded-full bg-brand-accent/10 flex items-center justify-center text-brand-accent">
                                <i class="bi bi-truck text-xl"></i>
                            </div>
                            <span class="text-xs text-gray-400">Fast Delivery</span>
                        </div>
                    </div>
                </div>

                <!-- Need Help -->
                <div class="glass-panel rounded-2xl p-4 border border-white/10 text-center">
                    <p class="text-sm text-gray-400 mb-3">Need help with your order?</p>
                    <a href="#" class="text-brand-accent hover:text-white transition-colors text-sm font-medium flex items-center justify-center gap-1">
                        <i class="bi bi-headset"></i> Contact Support
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

{{-- Recently Viewed --}}
@if(!empty($recentProducts) && $recentProducts->count())
<section class="py-16 border-t border-white/10 mt-12">
    <h2 class="text-2xl font-bold mb-8 flex items-center gap-2">
        <i class="bi bi-clock-history text-brand-accent"></i> Recently Viewed
    </h2>

    <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
        @foreach($recentProducts as $item)
        <a href="{{ $item['url'] }}"
            class="group rounded-xl border border-white/5 bg-white/[0.02] p-4 hover:border-brand-accent/30 transition-all hover:-translate-y-1"
            data-id="{{ $item['id'] }}"
            data-price="{{ $item['price'] }}"
            data-qty="1">
            <div class="aspect-square rounded-lg bg-white/5 mb-4 overflow-hidden">
                <img src="{{ $item['image'] }}"
                    class="w-full h-full object-cover opacity-70 group-hover:opacity-100 group-hover:scale-110 transition-all duration-500"
                    alt="{{ $item['name'] }}">
            </div>
            <h4 class="text-sm font-medium text-white group-hover:text-brand-accent transition-colors truncate">
                {{ $item['name'] }}
            </h4>
            <div class="text-sm font-bold text-brand-accent mt-1">
                AED {{ number_format($item['price']) }}
            </div>
        </a>
        @endforeach
    </div>
</section>
@endif

@endsection